version: "3.8"

services:
  postgresql:
    container_name: gdsc_movie_api_db
    ports:
      - 5432:5432
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - api_network
    environment:
      - POSTGRES_PASSWORD=000000
  server:
    container_name: gdsc_movie_api
    ports:
      - 8080:8080
    image: node:16
    networks:
      - api_network
    depends_on:
      - postgresql
    volumes:
      - .:/app

networks:
  api_network:
    name: api_network

volumes:
  pgdata:
    name: pgdata
