version: '3.9'

services:
  postgresql:
    container_name: gdsc_movie_api_db
    ports:
      - 5432:5432
    image: postgres:14
    networks:
      - api_network
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=movie_api
  server:
    container_name: gdsc_movie_api
    build: .
    ports:
      - 8080:8080
    networks:
      - api_network
    depends_on:
      - postgresql
    environment:
      - DATABASE_URL=postgresql://root:root@postgresql:5432/movie_api
      - PORT=8080

networks:
  api_network:
    name: api_network

volumes:
  pgdata:
    name: gdsc_movie_api_pgdata
  apidata:
    name: gdsc_movie_api_data
